[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Products"
url = "/products/"
identifier = "products"
weight = 10

  [[main]]
  name = "Pallets"
  url = "/products/pallet/"
  identifier = "products-style"
  parent = "products"
  weight = 11

  [[main]]
  name = "Crates"
  url = "/products/crate/"
  identifier = "products-load"
  parent = "products"
  weight = 12

  [[main]]
  name = "Waste Bins"
  url = "/products/waste/"
  identifier = "products-dimension"
  parent = "products"
  weight = 13

[[main]]
name = "Industries"
url = "/industries/"
identifier = "industries"
weight = 20

  [[main]]
  name = "Cold Chain Logistics Solutions"
  url = "/industries/cold-chain/"
  parent = "industries"
  weight = 21

  [[main]]
  name = "High-Bay Racking Storage Solutions"
  url = "/industries/warehousing/"
  parent = "industries"
  weight = 22

  [[main]]
  name = "Export One-Way Pallets"
  url = "/industries/export/"
  parent = "industries"
  weight = 23

  [[main]]
  name = "Food-Grade Pallet Applications"
  url = "/industries/food-grade/"
  parent = "industries"
  weight = 24

  [[main]]
  name = "Chemical & Hazardous Goods Storage"
  url = "/industries/chemical/"
  parent = "industries"
  weight = 25

[[main]]
name = "Resources"
url = "/resources/"
identifier = "resources"
weight = 30

  [[main]]
  name = "Blog"
  url = "/resources/articles/"
  parent = "resources"
  weight = 31

  [[main]]
  name = "News"
  url = "/resources/news/"
  parent = "resources"
  weight = 32

  [[main]]
  name = "Downloads"
  url = "/resources/downloads/"
  parent = "resources"
  weight = 33

  [[main]]
  name = "FAQ"
  url = "/resources/faq/"
  parent = "resources"
  weight = 34

[[main]]
name = "About Us"
url = "/about/"
identifier = "about"
weight = 40

[[main]]
name = "Contact Us"
url = "/contact/"
identifier = "contact"
weight = 50
